version: '3.9'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus.yml
    networks:
      - monitoring_network

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring_network

  api:
    container_name: api
    build:
      context: ../services/api
    ports:
      - "8000:8000"
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge