name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get remove -y containerd containerd.io
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          cd services/api
          docker build -t test-api .

      - name: Push Docker image to Docker Hub (optional)
        run: |
          docker tag test-api andydck/ci-cd-plateforme:tag
          docker push andydck/ci-cd-plateforme:tag